export const Tips: string[] = [
    "Did you know that specifying which blockchain you're querying can lead to more accurate data? Keeping our conversations blockchain-specific reduces ambiguity.",
    "Discovered a product issue? Submitting feedback may earn you extra Scopepoints! We appreciate users who help us improve.",
    "When exploring, try selecting a particular token or project to narrow your focus. ScopeChat's answers become more precise with a defined context.",
    "Crypto projects often share similar names. Checking associated chains and contract addresses helps clearly identify targets.",
    "Well-crafted prompts align AI capabilities with your intent. Recommended prompts optimize output quality.",
    "Smart Money wallets obtain high returns through trades, making their portfolios and transactions alpha-rich goldmines.",
    "Exchange inflow and outflow data reveals asset movements between high and low liquidity venues.",
    "Large transfers commonly coincide with token price changes.",
    "Significant token price shifts may cascade across related sectors.",
    "ROI, which measures return on investment, is a key metric for assessing performance.",
    "It's always good to take profit at any time, crypto investment is super risky and profitable at the same time.",
    "The best time to take profit is when you want to share your profit screenshot to others",
    "Adding $ or 'Token' will let you get more token related data, sometimes the token and the project it belongs to share the same name.",
    "If you come across unfamiliar crypto jargon or terms, ask the chat bot to define or explain them. This helps you deepen your knowledge and avoid misunderstandings.",
    "If you find a token you want to trade, always remeber to double-check the token contract address and project information, you don't want to waste your money",
    "Exchange deposits usually means the depositer want to find some place to sell the coins, but that's not always the case.",
    "Invest only what you can afford to lose, cryptocurrency investments can be volatile.",
    "Specify the time and token when asking Scopechat to make a moneyflow for you.",
    "Whales use multiple addresses to avoid being tracked, ask Scopechat to find related addresses for you.",
    "While diversification is essential, don’t overextend yourself by investing in too many projects.",
    "Not your key, not your coin. Either Scopechat nor 0xScope team will ask for your private key. Stay frosty in the dark forest.",
    "Before investing, ask Scopechat for the most recent token unlock event.",
]

export const TipsZh: string[] = [
    `明確指出您正在查詢的區塊鏈可以提高數據的準確性,這你知道嗎? 保持我們對話的區塊鏈特定性可以減少模糊性。`,
    '發現產品問題? 提交反饋可以為您獲得額外的Scope點數! 我們感謝能幫助我們改進的用戶。',
    `在探索時,嘗試選擇特定的代幣或項目以縮小您的關注範圍。 ScopeChat的答案在明確的上下文中會更精確。`,
    '加密項目經常共用相似的名稱。 查看相關的鏈和合約地址有助於清晰地識別目標。',
    '編寫精良的提示可以使AI功能與您的意圖保持一致。 建議的提示可以優化輸出質量。',
    '機智資金錢包通過交易獲得高回報,使其投資組合和交易變成富含阿爾法的金礦。',
    '交易所的流入和流出數據揭示了高流動性和低流動性場所之間的資產流動。',
    '大額轉賬通常與代幣價格變動同時發生。',
    '代幣價格的顯著變動可能會在相關行業間級聯傳播。',
    '投資回報率是衡量績效的關鍵指標。',
    `隨時獲利總是好的,加密貨幣投資風險非常大,同時也具有可觀的盈利空間。`,
    '最佳獲利時機是當您想與他人分享溢利截圖時',
    `添加 $ 或 'Token' 將使您獲得更多與代幣相關的數據,有時代幣和它所屬的項目共用相同的名稱。`,
    '如果您遇到不熟悉的加密術語或詞彙,請讓聊天機器人進行定義或解釋。 這將幫助您深化知識並避免誤解。',
    `如果您找到想要交易的代幣,記住要仔細檢查代幣合約地址和項目信息,您不想浪費金錢。`,
    `交易所存款通常意味著存款人想找個地方賣出幣,但情況並非總是如此。`,
    '只投資您所能承受的損失,加密貨幣投資可能會波動。',
    '在要求Scopechat為您製作資金流動圖時,請指定時間和代幣。',
    '鯨魚使用多個地址來避免被跟蹤,讓Scopechat為您找到相關地址。',
    '雖然多元化投資必不可少,但不要投資過多項目而超出自己的承受能力。',
    '不是你的密鑰,不是你的幣。 Scopechat和0xScope團隊都不會要求您的私鑰。 在黑暗的森林中保持清醒。',
    '在投資之前,請Scopechat查詢最新代幣解鎖事件。',
]